version: '3.8'

services:
  # PostgreSQL for integration tests
  postgres_test:
    image: postgres:15-alpine
    container_name: eventhub_postgres_test
    environment:
      POSTGRES_DB: eventhub_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MySQL for integration tests (alternative)
  mysql_test:
    image: mysql:8.0
    container_name: eventhub_mysql_test
    environment:
      MYSQL_DATABASE: eventhub_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for cache tests
  redis_test:
    image: redis:7-alpine
    container_name: eventhub_redis_test
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ for messenger tests
  rabbitmq_test:
    image: rabbitmq:3-management-alpine
    container_name: eventhub_rabbitmq_test
    environment:
      RABBITMQ_DEFAULT_USER: test_user
      RABBITMQ_DEFAULT_PASS: test_pass
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
  mysql_test_data:
