services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
      - "8443:443"
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - mercure
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://eventhub:secret@postgres:5432/eventhub
      - MESSENGER_TRANSPORT_DSN=redis://redis:6379/messages
      - MAILER_DSN=smtp://mailhog:1025
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=eventhub
      - RABBITMQ_PASSWORD=secret
      - MERCURE_URL=http://mercure/.well-known/mercure
      - MERCURE_PUBLIC_URL=http://localhost:3000/.well-known/mercure
      - MERCURE_JWT_SECRET=!ChangeThisMercureHubJWTSecretKey!
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - mercure
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_MERCURE_URL=http://localhost:3000/.well-known/mercure

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: eventhub
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: eventhub
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  mercure:
    image: dunglas/mercure:v0.15
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Allow anonymous subscriptions (for development)
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:5173
        anonymous
    ports:
      - "3000:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  mercure_data:
  mercure_config: