api_platform:
    title: 'EventHub API'
    version: '1.0.0'
    description: 'Event management and ticketing system API'
    
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']  # Dodano obsługę formatu JSON-LD
        
    docs_formats:
        jsonapi: ['application/vnd.api+json']
        jsonld: ['application/ld+json']  # Dodano do formatów dokumentacji
        
    swagger:
        versions: [3]
        
    collection:
        pagination:
            enabled: true
            page_parameter_name: page
            items_per_page_parameter_name: itemsPerPage  # Maps to ?itemsPerPage= in API requests
            
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
        
    patch_formats:
        json: ['application/merge-patch+json']
        
    use_symfony_listeners: true

    # Set default pagination values globally (optional)
    defaults:
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 100