gesdinet_jwt_refresh_token:
    # Refresh token configuration
    refresh_token_class: App\Entity\RefreshToken
    
    # TTL for refresh tokens (30 days = 2592000 seconds)
    ttl: 2592000
    
    # Update TTL on token refresh (extends expiration on each use)
    ttl_update: true
    
    # Single use tokens (more secure - token can only be used once)
    single_use: true
    
    # Token parameter name in request body
    token_parameter_name: refresh_token
