framework:
    messenger:
        failure_transport: failed

        transports:
            sync: 'sync://'
            async:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: 'async'
            high_priority:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: 'high_priority'
            notifications:
                dsn: '%env(REDIS_URL)%'
                options:
                    stream: 'notifications'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\Command\Payment\*': high_priority
            'App\Message\Command\*': async
            'App\Message\Query\*': sync
            'App\Message\Event\*': notifications

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus: ~
