name: CI

on: [push, pull_request]

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer
          extensions: mbstring, iconv


      - name: Install dependencies
        run: cd backend && composer install --no-interaction --no-progress --prefer-dist

      - name: Install PHPStan
        run: cd backend && composer require --no-interaction --no-progress --dev phpstan/phpstan:^1.11

      - name: Validate composer.json
        run: cd backend && composer validate --no-check-publish

      - name: Run PHPUnit (Unit Tests)
        run: cd backend && vendor/bin/phpunit tests/Unit --testdox
        
      - name: Test Summary
        run: cd backend && vendor/bin/phpunit tests/Unit --no-coverage

      - name: Run PHPStan
        run: cd backend && vendor/bin/phpstan analyse -c phpstan.neon

      - name: Deptrac (if available)
        run: |
          cd backend
          if [ -x vendor/bin/deptrac ]; then vendor/bin/deptrac --config=../deptrac.yaml; else echo "deptrac not installed"; fi

      - name: Rector dry-run (if available)
        run: |
          cd backend
          if [ -x vendor/bin/rector ]; then vendor/bin/rector process --dry-run -c ../rector.php; else echo "rector not installed"; fi

      - name: Bump PHPStan level to 5
        run: |
          cd backend
          sed -i 's/level: 4/level: 5/' phpstan.neon || true
