name: CI

on: [push, pull_request]

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer
          extensions: mbstring, iconv

      - name: Configure Composer GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: composer config -g github-oauth.github.com "$GITHUB_TOKEN"


      - name: Sync dev tools lock (deptrac, rector, lcobucci/clock)
        run: cd backend && composer update --no-interaction --no-progress --prefer-dist -W qossmic/deptrac-shim rector/rector lcobucci/clock

      - name: Install dependencies
        run: cd backend && composer install --no-interaction --no-progress --prefer-dist


      - name: Validate composer.json
        run: cd backend && composer validate --no-check-publish

      - name: Run PHPUnit (Unit Tests)
        run: cd backend && vendor/bin/phpunit tests/Unit --testdox
        
      - name: Test Summary
        run: cd backend && vendor/bin/phpunit tests/Unit --no-coverage

      - name: Run PHPStan
        run: cd backend && composer require --no-interaction --no-progress --dev -W phpstan/phpstan:^1.11 && vendor/bin/phpstan analyse -c phpstan.neon

      - name: Deptrac (non-blocking if present)
        run: |
          cd backend
          if [ -x vendor/bin/deptrac ] && [ -f "$GITHUB_WORKSPACE/deptrac.yaml" ]; then \
            vendor/bin/deptrac analyze --config-file=$GITHUB_WORKSPACE/deptrac.yaml \
            || vendor/bin/deptrac analyse --config-file=$GITHUB_WORKSPACE/deptrac.yaml \
            || vendor/bin/deptrac --config-file=$GITHUB_WORKSPACE/deptrac.yaml \
            || vendor/bin/deptrac --config=$GITHUB_WORKSPACE/deptrac.yaml \
            || echo "Deptrac failed (non-blocking)"; \
          else \
            echo "Deptrac skipped (binary or config missing)"; \
          fi

      - name: Rector dry-run (if available)
        run: |
          cd backend
          if [ -x vendor/bin/rector ]; then vendor/bin/rector process --dry-run -c ../rector.php; else echo "rector not installed"; fi

      - name: Bump PHPStan level to 5
        run: |
          cd backend
          sed -i 's/level: 4/level: 5/' phpstan.neon || true
