name: CI

on: [push, pull_request]

jobs:
  php:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: eventhub_test
          POSTGRES_USER: eventhub
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U eventhub"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      APP_ENV: test
      DATABASE_URL: postgresql://eventhub:secret@localhost:5432/eventhub_test
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer
          extensions: mbstring, iconv

      - name: Configure Composer GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: composer config -g github-oauth.github.com "$GITHUB_TOKEN"



      - name: Validate composer.json
        run: cd backend && composer validate --no-check-publish

      - name: Install dependencies
        run: cd backend && composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare test database
        run: |
          cd backend
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:schema:update --force --env=test

      - name: Run PHPUnit (All Tests)
        run: cd backend && SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/phpunit
        

      - name: Run PHPStan
        run: cd backend && vendor/bin/phpstan analyse -c phpstan.neon

      - name: Deptrac (non-blocking if present)
        run: |
          cd backend
          if [ -x vendor/bin/deptrac ] && [ -f "$GITHUB_WORKSPACE/deptrac.yaml" ]; then \
            vendor/bin/deptrac analyze --config-file=$GITHUB_WORKSPACE/deptrac.yaml \
            || vendor/bin/deptrac analyse --config-file=$GITHUB_WORKSPACE/deptrac.yaml \
            || vendor/bin/deptrac --config-file=$GITHUB_WORKSPACE/deptrac.yaml \
            || vendor/bin/deptrac --config=$GITHUB_WORKSPACE/deptrac.yaml \
            || echo "Deptrac failed (non-blocking)"; \
          else \
            echo "Deptrac skipped (binary or config missing)"; \
          fi

      - name: Rector dry-run (if available)
        run: |
          cd backend
          if [ -x vendor/bin/rector ]; then vendor/bin/rector process --dry-run -c ../rector.php; else echo "rector not installed"; fi

